### ISSUE TITLE
ElasticSearch

### ISSUE THREAD

**Issue by koizo** [PredictionIO/template-scala-parallel-universal-recommendation#24]
Is it possible to use a remote ElasticSearch cluster with this template?
I configured the pio-env with:
PIO_STORAGE_REPOSITORIES_METADATA_NAME=pio_meta
PIO_STORAGE_REPOSITORIES_METADATA_SOURCE=ELASTICSEARCH

PIO_STORAGE_SOURCES_ELASTICSEARCH_TYPE=elasticsearch
PIO_STORAGE_SOURCES_ELASTICSEARCH_CLUSTERNAME=xxx
PIO_STORAGE_SOURCES_ELASTICSEARCH_HOSTS=xx.xx.xx.xx
PIO_STORAGE_SOURCES_ELASTICSEARCH_PORTS=9300
PIO_STORAGE_SOURCES_ELASTICSEARCH_HOME=/root/PredictionIO/vendors/elasticsearch-1.4.4

After train, the index appears on the ELK cluster, but always empty.

Best Regards

**Comment by pferrel** [comment]
Yes, name each host comma delimited no spaces, also list ports comma delimited no spaces so like this

PIO_STORAGE_SOURCES_ELASTICSEARCH_CLUSTERNAME=<my-cluster-name>
PIO_STORAGE_SOURCES_ELASTICSEARCH_HOSTS=xx.xx.xx.xx,xx.xx.xx.xx,xx.xx.xx.xx
PIO_STORAGE_SOURCES_ELASTICSEARCH_PORTS=9300,9300,9300

Also you need to change the cluster name in elasticsearch.yml but you will loose app metadata so backup with `pio export ...` and remove all apps, then change the ES config and re-create apps with `pio app new <appname>` and `pio import ...` the data into new config

Please address these questions to the Google Group, where this has been answered before.
