### ISSUE TITLE
Negative bias filtering not working.

### ISSUE THREAD

**Issue by AbhilashNagabhushan** [PredictionIO/template-scala-parallel-universal-recommendation#28]
According to document the negative bias should filter out all properties except values which are passed as part of query.
But when giving a negative bias it is returning empty result set.

**Comment by pferrel** [comment]
then there are no recommended items with **all** of the property values you specified. This is why you should use boosts, since they will favor items with **some** of the values you specify but return results even if there are none

BTW, please use the google group for questions.
