### ISSUE TITLE
Problems training With Elasticsearch Cluster

### ISSUE THREAD

**Issue by voran** [PredictionIO/template-scala-parallel-universal-recommendation#33]
Hello,

We have PredictionIO set up in production using an elasticsearch cluster. We have the following elasticsearch config in pio-env.sh:

```
PIO_STORAGE_SOURCES_ELASTICSEARCH_TYPE=elasticsearch
PIO_STORAGE_SOURCES_ELASTICSEARCH_CLUSTERNAME="predictionio"
PIO_STORAGE_SOURCES_ELASTICSEARCH_HOSTS="eu-west-elasticsearch01,eu-west-elasticsearch02"
PIO_STORAGE_SOURCES_ELASTICSEARCH_PORTS="9300,9300"
```

However, when I try to train the engine we get an exception and we see it's trying to connect to elasticsearch at localhost:9200. (see attached stacktrace)

Is there any extra configuration that we are missing?
[stacktrace.txt](https://github.com/PredictionIO/template-scala-parallel-universal-recommendation/files/110942/stacktrace.txt)

Thanks,
Yavor

**Comment by pferrel** [comment]
Answered on the user list. The Spark-Hadoop lib from Elasticsearch uses the REST API to write to ES from Spark. You can pass in nodes and port via the sparkConf section of the UR's engine.json
