### ISSUE TITLE
No matter what I do, I always get empty item array in response with 0 score

### ISSUE THREAD

**Issue by armahajan** [PredictionIO/template-scala-parallel-universal-recommendation#4]
Here is the output I get every time
{
itemScores: [0]
}

For any query... as simple as 
{
  "user": "akshaym@ignitiv.com"
}

I have 30+ users in the db added using $set events, 500+ items added using $set events, 150+ view events where entityId and targetEntityId do match users and items from the $set added entities. I also have similar purchase events (20+). The engine trains successfully. What I could be doing wrong? Below is my engine.json.

{
  "id": "default",
  "description": "Default settings",
  "engineFactory": "com.abc.RecommendationEngine",
  "datasource": {
    "params" : {
      "name": "sample-handmade-data.txt",
      "appName": "univrecoengine",
      "eventNames": ["purchase", "view"]
    }
  },
  "sparkConf": {
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer",
    "spark.kryo.registrator": "org.apache.mahout.sparkbindings.io.MahoutKryoRegistrator",
    "spark.kryo.referenceTracking": "false",
    "spark.kryoserializer.buffer.mb": "300",
    "spark.executor.memory": "1g",
    "es.index.auto.create": "true"
  },
  "algorithms": [
    {
      "comment": "setup for example 'handmade' data, make sure to change for your needs",
      "name": "ur",
      "params": {
        "appName": "univrecoengine",
        "indexName": "urindex",
        "typeName": "items",
        "eventNames": ["purchase", "view"]
      }
    }
  ]
}

Sample user:
{
eventId: "1d5a25d59e064a469da5088f053f0b6b"
event: "$set"
entityType: "user"
entityId: "akshaym@ignitiv.com"
properties: {}
eventTime: "2015-01-23T16:17:26.910Z"
creationTime: "2015-07-30T12:29:08.156Z"
}

Sample item:
{"eventId":"17182672ea034769a7f7f52bf92ac0bd","event":"$set","entityType":"item","entityId":"ACR_CLR","properties":{"categories":["143"],"producttype":["36"]},"eventTime":"2015-02-13T01:10:57.642Z","creationTime":"2015-07-30T12:32:09.991Z"}

Sample View:
{"eventId":"ce0874b2c5da4b309be2ce375be3d595","event":"view","entityType":"user","entityId":"akshaym@ignitiv.com","targetEntityType":"item","targetEntityId":"ACR_CLR","properties":{},"eventTime":"2015-07-30T12:35:50.000Z","creationTime":"2015-07-30T12:35:58.695Z"}

**Comment by armahajan** [comment]
Basically we are totally unaware if this engine uses standard event API provided by PredictionIO. Here is the output of engine from logs

[INFO] [URAlgorithm] Query received, user id: Some(akshaym@ignitiv.com), item id: None
[INFO] [URAlgorithm] Query:
{"size":20,"query":{"bool":{"should":[{"terms":{"purchase":["ACR_CLR1","ACR_CLR2","ACR_CLR","ACR_CLR","ACR_CLR","ACR_CLR","ACR_CLR","ACR_CLR","ACR_CLR"]}},{"terms":{"view":["ACR_CLR1","ACR_CLR2","ACR_CLR1","ACR_CLR","ACR_CLR2"]}}],"must":[]}}}

[INFO] [esClient$] Results: 0 retrieved of a possible 0

**Comment by pferrel** [comment]
You must have a "primary" event as the first in the list. Since you have no "purchase" event the UR will have nothing to correlate the secondary "view" event with. The first in the array is very important, the rest are considered secondary and are very important too but are used int he recs calcluation differently and will produce not results without the primary. BTW the best place to get hep with things like this is PredictionIO Google Groups/mailing list.

If you have only "view" with exactly that string as an event name try setting:

```
"eventNames": ["view"]
```

BTW the duplicate items in the query is a bug fixed in v0.2.0, which should be released next week and is available on the v0.2.0 branch. It has little if any effect on recommendations but slows the query a tiny bit.

**Comment by pferrel** [comment]
If this issue has been resolved please let me know so I can clear it.

**Comment by armahajan** [comment]
Yes sure.

**Comment by pferrel** [comment]
Unclear documentation has been updated to clearly point to need for the primary action data.
