### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by tobilg** [PredictionIO/template-scala-parallel-universal-recommendation#51]
No text.

**Comment by pferrel** [comment]
This fork is deprecated. It is very much a live project with lots of deployments and support.
- code: https://github.com/actionml/template-scala-parallel-universal-recommendation
- support: https://groups.google.com/forum/#!forum/actionml-user

PredictionIO is now an Apache project (so this github repo is deprecated and moved to https://github.com/apache/incubator-predictionio). It is moving through the release process at Apache and the Universal Recommender will support that when it's released. Until then install PIO from the AML fork (already merged with the new Apache release) here: actionml.com/docs/install

**Comment by tobilg** [comment]
Thanks for the fast feedback @pferrel 

May I suggest that you write this in the README.md as well? I think it would make things clearer. Also, one really gets the impression that this project is abandoned, because PRs and issues are not closed/handled, and this was already the case before it was given to Apache. A hint on the "frontpage" would be nice.

Thanks again for your work!

**Comment by pferrel** [comment]
Prediction.io now redirects to the Apache site. I'll ask them to add the notice to the UR readme.md but I don't have access to this github anymore.

Sorry for the confusion, I think more people are working on this than ever before. The old pio google group also has a prominent notice of the move.
