### ISSUE TITLE
PredictionIO 0.11.0

### ISSUE THREAD

**Issue by ftopan80** [PredictionIO/template-scala-parallel-universal-recommendation#59]
Hi guys, I tried to compile and use the new PredictionIO ver 0.11.0, but there was multiple import error while doing 'pio build'
Is it not compatible yet with current universal-recommendation version?
please advise thx

**Comment by pferrel** [comment]
This repo is long deprecated but I don't have the rights to remove it.

For Universal Recommender support go here: https://groups.google.com/forum/#!forum/actionml-user

For the latest UR, that is compatible with Apache PIO 0.10.0 go here: https://github.com/actionml/universal-recommender

Documents here: http://actionml.com/ur

**Comment by ftopan80** [comment]
I see... Thank You
