### ISSUE TITLE
Seem to be stuck in pio build

### ISSUE THREAD

**Issue by chrismark** [PredictionIO/template-scala-parallel-universal-recommendation#6]
I seem to be stuck in 'pio build'. Last line in the log output says 'Going to run /path/to/sbt/sbt package assemblyPackageDependency'.

Here's what I did:
1) edited 'appName' to 'testapp' in engine.json
2) ran 'pio app new testapp'
3) ran python examples/import_handmade_eventserver.py --access_key <accesskey>
(there's no examples/import_handmade.py but there's that one and seems to have ran fine.)
4) didn't do anything here. As I understand it's same as (1)
5) ran 'pio build'

I'm using a netbook/ubuntu 14.04 with 2GB memory

Is there something that I missed?

Thanks.

**Comment by tom-chan** [comment]
Did you try "pio build --verbose"? On the first run it will take longer to download all the dependencies.

**Comment by chrismark** [comment]
@tom-chan  Haven't not tried that. Thanks. Now it looks like it's doing something.
